#!/bin/bash
curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
sudo apt-get install speedtest
clear
echo ""
echo ""
echo " CÀI ĐẶT SPEEDTEST THÀNH CÔNG "
echo ""
#echo " Bạn bấm Y để đồng ý với giấy phép nếu là cài đặt lần đầu nó sẽ hỏi " 
echo ""
speedtest && yes
echo ""
