#!/usr/bin/bash
menu_speedtest()
{
        HOME="v4.3.2"  #Version
	echo " "                                  
	echo " =============================================="
	echo " =================== ĐẬU ĐẬU ==========["$HOME"]"
	echo " =.•♫•♬•.•♫•♬•  MENU SPEEDTEST  •♫•♬•.•♫•♬•.="
	echo " =============================================="
	echo " = (1). Menu X-Ui                             ="
	echo " = (2). Menu Speedtest                        ="
	echo " = (3). Menu tăng tốc VPS                     ="
	echo " = (4). Đổi mật khẩu VPS                      ="
	echo " = (5). Cập nhật VPS                          ="
	echo " = (6). Cập nhật Menu                         ="
	echo " = (7). Thông Báo mới                         ="
	echo " = (0). Đóng menu                             ="
	echo " =============================================="
	echo -n "  Lựa chọn của bạn là: "
	read so

	if [ $so -eq 1 ]
	then
        clear
        curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
        sudo apt-get install speedtest 
        clear
        menu_speedtest
        
	elif [ $so -eq 2 ]
	then
	echo " ---------------------------------------------- "
	echo "  Bấm Y để đồng ý "
	echo " ---------------------------------------------- "
        speedtest
        clear
        menu_speedtest

	elif [ $so -eq 0 ]
	then
        clear
        echo " "
        echo " =========== Ơ Kìa Sao Lại Đóng Menu =========== "
        echo " "
        echo "  Nếu Muốn Thử Lại Hãy Nhập Lệnh:  speedtest "
        echo " ------------------------------------------------------- "
        echo "  YTB: https://www.youtube.com/channel/UCly-jPYF0jWZS12IdyVZqsg/featured "
        echo "  FB: https://www.facebook.com/daudau.432/ "
	echo "  Github: https://github.com/DauDau432 "
        echo "  Zalo: 0983538806 "
        echo " ------------------------------------------------------- "
        exit 
               
	else
        clear
        echo " "
        echo " === Số Bạn Chọn Không Có Trong Bảng Điều Khiển === "
        echo " "
        echo " ============ Chọn sai ời. chọn lại đi ============ "
        menu_speedtest
	fi
}

