#!/bin/bash
curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
sudo apt-get install speedtest
echo ""
echo ""
echo " Cài Đặt Speedtest Thành Công "
echo ""
echo " Bạn Bấm Y Để Đồng Ý Giấy Phép Nếu Chương Trình Hỏi " 
echo ""
speedtest
echo ""
